### ISSUE TITLE
Not generating locales

### ISSUE THREAD

**Issue by selankon** [naver/jsdoc-to-mdx#11]
Doing

```
npx jsdoc-to-mdx -c jsdoc-to-mdx.config.json -l es
```

With this config: 

```
{
  "locales": [],
  "outDir": "./temp_docs",
  "localesDir": "./temp_docs/i18n/{locale}/docusaurus-plugin-content-docs/current/sdk",
  "sidebar": "./temp_docs",
  "prefix": "sdk/",
  "jsdoc": "./jsdoc.json"
}
```

Is not generating the `./temp_docs/i18n/` files, and no error message. Is something wrong?

Thanks in advance

**Comment by WoodNeck** [comment]
You have to add the language you're using at `"locales"` in config.
Check the working repo and its config:
- https://github.com/naver/egjs-flicking
- https://github.com/naver/egjs-flicking/blob/master/jsdoc-to-mdx.json

**Comment by selankon** [comment]
Oh right! I forgot this!
