### ISSUE TITLE
Global functions

### ISSUE THREAD

**Issue by birdofpreyru** [naver/jsdoc-to-mdx#4]
It looks like a great library! One caveat I came across: it does not include global functions (and I guess some other global objects) into documentation. That is because the only global objects collected in the current version are: classes, interfaces, namespaces, constants, and typedefs; while functions are only picked up if they are members of some of those global objects. I guess, that should be super-easy to correct, if there is no particular reasons to omit them?

**Comment by WoodNeck** [comment]
Hello @birdofpreyru!
This module is tested only by [Flicking](https://naver.github.io/egjs-flicking/) and [InfiniteGrid](https://naver.github.io/egjs-infinitegrid/) by now, so it's just not fully tested on all other kinds of source codes.
There's no reason to omit it, I should fix that :)
